name: Automated test
on:
  pull_request:
    paths: 
      - '**.tsx'
      - '**.ts' 
    branches:
      - "master"
jobs:
  test-job:
    name: Build app and run tests
    runs-on: ubuntu-latest
    steps:
      - name: Install node-js 22
        uses: actions/setup-node@v4
        with:
          node-version: '22'
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Install dependencies
        run: npm ci
      - name: Run tests
        run: npm run test
      - name: Run linting
        run: npm run lint
      - name: Run Build
        run: npm run build